name: CI

on:
  pull_request:
     types:
      - opened
      - reopened
      - synchronize
      - closed
     branches:
      - develop
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      SUPABASE_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4

      - uses: supabase/setup-cli@v1
        with:
          version: latest

      - run: supabase link --project-ref $SUPABASE_PROJECT_ID

      - name: Save users data
        run: |
          psql "postgres://postgres.fnctwfmvvvfjctpwkdot:${{ secrets.STAGING_DB_PASSWORD }}@aws-0-us-west-1.pooler.supabase.com:5432/postgres" -c "SELECT * FROM users" > users_data.sql

      - run: supabase db push --include-all

      - run: supabase db reset --linked

      - name: Restore users data
        run: |
          cat users_data.sql | psql "postgres://postgres.fnctwfmvvvfjctpwkdot:${{ secrets.STAGING_DB_PASSWORD }}@aws-0-us-west-1.pooler.supabase.com:5432/postgres" -c "COPY users FROM stdin"
